# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c960ead5-c4ac-4487-98c1-a81b1ad96186";
      fsType = "btrfs";
      options = [ "subvol=@" "ssd" "noatime" "compress=zstd:3" "space_cache=v2" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5B7D-8309";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  services.resolved.enable = false;
  services.smartdns = {
    enable = true;
    settings = {
      dualstack-ip-selection = "yes";
      speed-check-mode = "ping,tcp:80";

      server-https = [
        "https://dns.alidns.com/dns-query"
        "https://doh.pub/dns-query"
      ];

      server = [
        "223.5.5.5"
        "119.29.29.29"
        "114,114,114,114"
      ];

      # domain-rules = [
      #   "/battle.net/ -speed-check-mode tcp:80"
      #   "/blizzard.com/ -speed-check-mode tcp:80"
      # ];
    };
  };

  networking.nameservers = [ "127.0.0.1" ];
  networking.networkmanager.dns = "none";


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
